---
- hosts: localhost
  tasks:
   - name: Create a login user
     user:
        name: challenge
        password: 'Bluesky123'
        groups: wheel
        state: present
        shell: /bin/bash
        system: no
        createhome: yes
        home: /home/challenge
