---
- hosts: challenge
  tasks:
    - name: Create a login user
      become: true
      become_method: sudo
      become_user: root
      user:
        name: challenge
        password: '$6$Admin456$RbY0/rkaU2kxAk66QYUNJX4HnU9MqNSESuu5VosCu1BEiDRU4eOEsiDqvXTdGkJcB3rfg0kH1dCNg/qK7jV09.'
        groups: wheel
        state: present
        shell: /bin/bash
        system: no
        createhome: yes
        home: /home/challenge

    - name: Add user to sudoers file
      become: true
      become_method: sudo
      become_user: root
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'